/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ScienceRouteImport } from './routes/science'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as WhereNowRouteImport } from './routes/where-now'
import { Route as HardwareSlugRouteImport } from './routes/hardware.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScienceRoute = ScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const WhereNowRoute = WhereNowRouteImport.update({
  id: '/where-now',
  path: '/where-now',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareSlugRoute = HardwareSlugRouteImport.update({
  id: '/hardware/$slug',
  path: '/hardware/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/credits': typeof CreditsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/science': typeof ScienceRoute
  '/timeline': typeof TimelineRoute
  '/where-now': typeof WhereNowRoute
  '/hardware/$slug': typeof HardwareSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/credits': typeof CreditsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/science': typeof ScienceRoute
  '/timeline': typeof TimelineRoute
  '/where-now': typeof WhereNowRoute
  '/hardware/$slug': typeof HardwareSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/credits': typeof CreditsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/science': typeof ScienceRoute
  '/timeline': typeof TimelineRoute
  '/where-now': typeof WhereNowRoute
  '/hardware/$slug': typeof HardwareSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badges'
    | '/credits'
    | '/login'
    | '/map'
    | '/profile'
    | '/science'
    | '/timeline'
    | '/where-now'
    | '/hardware/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badges'
    | '/credits'
    | '/login'
    | '/map'
    | '/profile'
    | '/science'
    | '/timeline'
    | '/where-now'
    | '/hardware/$slug'
  id:
    | '__root__'
    | '/'
    | '/badges'
    | '/credits'
    | '/login'
    | '/map'
    | '/profile'
    | '/science'
    | '/timeline'
    | '/where-now'
    | '/hardware/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  CreditsRoute: typeof CreditsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  ScienceRoute: typeof ScienceRoute
  TimelineRoute: typeof TimelineRoute
  WhereNowRoute: typeof WhereNowRoute
  HardwareSlugRoute: typeof HardwareSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science': {
      id: '/science'
      path: '/science'
      fullPath: '/science'
      preLoaderRoute: typeof ScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/where-now': {
      id: '/where-now'
      path: '/where-now'
      fullPath: '/where-now'
      preLoaderRoute: typeof WhereNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware/$slug': {
      id: '/hardware/$slug'
      path: '/hardware/$slug'
      fullPath: '/hardware/$slug'
      preLoaderRoute: typeof HardwareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  CreditsRoute: CreditsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  ScienceRoute: ScienceRoute,
  TimelineRoute: TimelineRoute,
  WhereNowRoute: WhereNowRoute,
  HardwareSlugRoute: HardwareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
